### ISSUE TITLE
WP-Optimize issue introduced in 2.5

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#385]
SiteOrigin Page Builder is having issues with WP-Optimize when it optimizes the data. Leading to a blank page:

![](https://i.imgur.com/FUSRbHE.png)

This issue disappears after its done (as in, the stylesheets load and this error doesn't occur) but if this page is cached by a plugin during this time, the user will have _major_ issues.

There are two different error notices, the first isn't so important:
> [12-Apr-2017 03:44:38 UTC] PHP Notice:  Use of undefined constant SITEORIGIN_PANELS_BASE_FILE - assumed 'SITEORIGIN_PANELS_BASE_FILE' in D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\widgets.php on line 466
> 
> [12-Apr-2017 03:44:38 UTC] PHP Stack trace:
> 
> [12-Apr-2017 03:44:38 UTC] PHP   1. {main}() D:\wamp\www\siteorigin\wp-admin\post.php:0
> 
> [12-Apr-2017 03:44:38 UTC] PHP   2. include() D:\wamp\www\siteorigin\wp-admin\post.php:173
> 
> [12-Apr-2017 03:44:38 UTC] PHP   3. require_once() D:\wamp\www\siteorigin\wp-admin\edit-form-advanced.php:473
> 
> [12-Apr-2017 03:44:38 UTC] PHP   4. do_action() D:\wamp\www\siteorigin\wp-admin\admin-header.php:118
> 
> [12-Apr-2017 03:44:38 UTC] PHP   5. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> 
> [12-Apr-2017 03:44:38 UTC] PHP   6. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> 
> [12-Apr-2017 03:44:38 UTC] PHP   7. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 03:44:38 UTC] PHP   8. SiteOrigin_Panels_Admin->enqueue_admin_scripts() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 03:44:38 UTC] PHP   9. SiteOrigin_Panels_Widget->form() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\admin.php:413
> 
> [12-Apr-2017 03:44:38 UTC] PHP  10. SiteOrigin_Panels_Widget->get_styles() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\widgets.php:217
> 
> [12-Apr-2017 03:44:38 UTC] PHP  11. SiteOrigin_Panels_Widget->get_widget_paths() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\widgets.php:501
> 
> [12-Apr-2017 03:44:38 UTC] PHP  12. SiteOrigin_Panels_Widget::get_widget_folders() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\widgets.php:448
> 

The second is an infinite loop:

> [12-Apr-2017 09:54:26 UTC] PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php on line 1356
> 
> [12-Apr-2017 09:54:26 UTC] PHP Stack trace:
> 
> [12-Apr-2017 09:54:26 UTC] PHP   1. {main}() D:\wamp\www\siteorigin\index.php:0
> 
> [12-Apr-2017 09:54:26 UTC] PHP   2. require() D:\wamp\www\siteorigin\index.php:17
> 
> [12-Apr-2017 09:54:26 UTC] PHP   3. require_once() D:\wamp\www\siteorigin\wp-blog-header.php:19
> 
> [12-Apr-2017 09:54:26 UTC] PHP   4. include() D:\wamp\www\siteorigin\wp-includes\template-loader.php:74
> 
> [12-Apr-2017 09:54:26 UTC] PHP   5. get_header() D:\wamp\www\siteorigin\wp-content\themes\vantage-free\home-panels.php:13
> 
> [12-Apr-2017 09:54:26 UTC] PHP   6. locate_template() D:\wamp\www\siteorigin\wp-includes\general-template.php:45
> 
> [12-Apr-2017 09:54:26 UTC] PHP   7. load_template() D:\wamp\www\siteorigin\wp-includes\template.php:643
> 
> [12-Apr-2017 09:54:26 UTC] PHP   8. require_once() D:\wamp\www\siteorigin\wp-includes\template.php:684
> 
> [12-Apr-2017 09:54:26 UTC] PHP   9. wp_head() D:\wamp\www\siteorigin\wp-content\themes\vantage-free\header.php:18
> 
> [12-Apr-2017 09:54:26 UTC] PHP  10. do_action() D:\wamp\www\siteorigin\wp-includes\general-template.php:2574
> 
> [12-Apr-2017 09:54:26 UTC] PHP  11. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> 
> [12-Apr-2017 09:54:26 UTC] PHP  12. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> 
> [12-Apr-2017 09:54:26 UTC] PHP  13. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  14. WPSEO_Frontend->head() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  15. do_action() D:\wamp\www\siteorigin\wp-content\plugins\wordpress-seo\frontend\class-frontend.php:670
> 
> [12-Apr-2017 09:54:26 UTC] PHP  16. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> 
> [12-Apr-2017 09:54:26 UTC] PHP  17. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> 
> [12-Apr-2017 09:54:26 UTC] PHP  18. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  19. WPSEO_OpenGraph->opengraph() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  20. do_action() D:\wamp\www\siteorigin\wp-content\plugins\wordpress-seo\frontend\class-opengraph.php:57
> 
> [12-Apr-2017 09:54:26 UTC] PHP  21. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> 
> [12-Apr-2017 09:54:26 UTC] PHP  22. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> 
> [12-Apr-2017 09:54:26 UTC] PHP  23. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  24. WPSEO_OpenGraph->description() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  25. get_the_excerpt() D:\wamp\www\siteorigin\wp-content\plugins\wordpress-seo\frontend\class-opengraph.php:639
> 
> [12-Apr-2017 09:54:26 UTC] PHP  26. apply_filters() D:\wamp\www\siteorigin\wp-includes\post-template.php:397
> 
> [12-Apr-2017 09:54:26 UTC] PHP  27. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\plugin.php:203
> 
> [12-Apr-2017 09:54:26 UTC] PHP  28. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300
> 
> [12-Apr-2017 09:54:26 UTC] PHP  29. wp_trim_excerpt() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300
> 
> [12-Apr-2017 09:54:26 UTC] PHP  30. apply_filters() D:\wamp\www\siteorigin\wp-includes\formatting.php:3296
> 
> [12-Apr-2017 09:54:26 UTC] PHP  31. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\plugin.php:203
> 
> [12-Apr-2017 09:54:26 UTC] PHP  32. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  33. SiteOrigin_Panels->generate_post_content() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  34. SiteOrigin_Panels_Renderer->render() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\siteorigin-panels.php:233
> 
> [12-Apr-2017 09:54:26 UTC] PHP  35. SiteOrigin_Panels_Renderer->render_row() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:288
> 
> [12-Apr-2017 09:54:26 UTC] PHP  36. SiteOrigin_Panels_Renderer->render_cell() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:666
> 
> [12-Apr-2017 09:54:26 UTC] PHP  37. SiteOrigin_Panels_Renderer->render_widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:738
> 
> [12-Apr-2017 09:54:26 UTC] PHP  38. SiteOrigin_Panels_Renderer->the_widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:779
> 
> [12-Apr-2017 09:54:26 UTC] PHP  39. SiteOrigin_Panels_Widgets_PostLoop->widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:482
> 
> [12-Apr-2017 09:54:26 UTC] PHP  40. locate_template() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\basic.php:324
> 
> [12-Apr-2017 09:54:26 UTC] PHP  41. load_template() D:\wamp\www\siteorigin\wp-includes\template.php:643
> 
> [12-Apr-2017 09:54:26 UTC] PHP  42. require() D:\wamp\www\siteorigin\wp-includes\template.php:686
> 
> [12-Apr-2017 09:54:26 UTC] PHP  43. get_template_part() D:\wamp\www\siteorigin\wp-content\themes\vantage-free\loop.php:18
> 
> [12-Apr-2017 09:54:26 UTC] PHP  44. locate_template() D:\wamp\www\siteorigin\wp-includes\general-template.php:167
> 
> [12-Apr-2017 09:54:26 UTC] PHP  45. load_template() D:\wamp\www\siteorigin\wp-includes\template.php:643
> 
> [12-Apr-2017 09:54:26 UTC] PHP  46. require() D:\wamp\www\siteorigin\wp-includes\template.php:686
> 
> [12-Apr-2017 09:54:26 UTC] PHP  47. the_excerpt() D:\wamp\www\siteorigin\wp-content\themes\vantage-free\content.php:46
> 
> [12-Apr-2017 09:54:26 UTC] PHP  48. get_the_excerpt() D:\wamp\www\siteorigin\wp-includes\post-template.php:362
> 
> [12-Apr-2017 09:54:26 UTC] PHP  49. apply_filters() D:\wamp\www\siteorigin\wp-includes\post-template.php:397
> 
> [12-Apr-2017 09:54:26 UTC] PHP  50. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\plugin.php:203
> 
> [12-Apr-2017 09:54:26 UTC] PHP  51. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300
> 
> [12-Apr-2017 09:54:26 UTC] PHP  52. wp_trim_excerpt() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:300
> 
> [12-Apr-2017 09:54:26 UTC] PHP  53. apply_filters() D:\wamp\www\siteorigin\wp-includes\formatting.php:3296
> 
> [12-Apr-2017 09:54:26 UTC] PHP  54. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\plugin.php:203
> 
> [12-Apr-2017 09:54:26 UTC] PHP  55. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  56. SiteOrigin_Panels->generate_post_content() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> 
> [12-Apr-2017 09:54:26 UTC] PHP  57. SiteOrigin_Panels_Renderer->render() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\siteorigin-panels.php:233
> 
> [12-Apr-2017 09:54:26 UTC] PHP  58. SiteOrigin_Panels_Renderer->render_row() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:288
> 
> [12-Apr-2017 09:54:26 UTC] PHP  59. SiteOrigin_Panels_Renderer->render_cell() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:666
> 
> [12-Apr-2017 09:54:26 UTC] PHP  60. SiteOrigin_Panels_Renderer->render_widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:738
> 
> [12-Apr-2017 09:54:26 UTC] PHP  61. SiteOrigin_Panels_Renderer->the_widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:779
> 
> [12-Apr-2017 09:54:26 UTC] PHP  62. SiteOrigin_Widget->widget() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\renderer.php:482
> 
> [12-Apr-2017 09:54:26 UTC] PHP  63. SiteOrigin_Widget->generate_and_enqueue_instance_styles() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\siteorigin-widget.class.php:168
> 
> [12-Apr-2017 09:54:26 UTC] PHP  64. SiteOrigin_Widget->save_css() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\siteorigin-widget.class.php:268
> 
> [12-Apr-2017 09:54:26 UTC] PHP  65. SiteOrigin_Widget->get_instance_css() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\siteorigin-widget.class.php:686
> 
> [12-Apr-2017 09:54:26 UTC] PHP  66. lessc->compile() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\siteorigin-widget.class.php:836
> 
> [12-Apr-2017 09:54:26 UTC] PHP  67. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:1807
> 
> [12-Apr-2017 09:54:26 UTC] PHP  68. lessc->compileRoot() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:193
> 
> [12-Apr-2017 09:54:26 UTC] PHP  69. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:278
> 
> [12-Apr-2017 09:54:26 UTC] PHP  70. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  71. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:658
> 
> [12-Apr-2017 09:54:26 UTC] PHP  72. lessc->compileCSSBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:196
> 
> [12-Apr-2017 09:54:26 UTC] PHP  73. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:222
> 
> [12-Apr-2017 09:54:26 UTC] PHP  74. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  75. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:658
> 
> [12-Apr-2017 09:54:26 UTC] PHP  76. lessc->compileCSSBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:196
> 
> [12-Apr-2017 09:54:26 UTC] PHP  77. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:222
> 
> [12-Apr-2017 09:54:26 UTC] PHP  78. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  79. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:658
> 
> [12-Apr-2017 09:54:26 UTC] PHP  80. lessc->compileCSSBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:196
> 
> [12-Apr-2017 09:54:26 UTC] PHP  81. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:222
> 
> [12-Apr-2017 09:54:26 UTC] PHP  82. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  83. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:658
> 
> [12-Apr-2017 09:54:26 UTC] PHP  84. lessc->compileCSSBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:196
> 
> [12-Apr-2017 09:54:26 UTC] PHP  85. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:222
> 
> [12-Apr-2017 09:54:26 UTC] PHP  86. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  87. lessc->compileBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:658
> 
> [12-Apr-2017 09:54:26 UTC] PHP  88. lessc->compileCSSBlock() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:196
> 
> [12-Apr-2017 09:54:26 UTC] PHP  89. lessc->compileProps() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:222
> 
> [12-Apr-2017 09:54:26 UTC] PHP  90. lessc->compileProp() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:284
> 
> [12-Apr-2017 09:54:26 UTC] PHP  91. lessc->findBlocks() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:684
> 
> [12-Apr-2017 09:54:26 UTC] PHP  92. lessc->findBlocks() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:595
> 
> [12-Apr-2017 09:54:26 UTC] PHP  93. lessc->findBlocks() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:595
> 
> [12-Apr-2017 09:54:26 UTC] PHP  94. lessc->findBlocks() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:595
> 
> [12-Apr-2017 09:54:26 UTC] PHP  95. lessc->findBlocks() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:595
> 
> [12-Apr-2017 09:54:26 UTC] PHP  96. lessc->patternMatchAll() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:572
> 
> [12-Apr-2017 09:54:26 UTC] PHP  97. lessc->patternMatch() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:553
> 
> [12-Apr-2017 09:54:26 UTC] PHP  98. lessc->zipSetArgs() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:470
> 
> [12-Apr-2017 09:54:26 UTC] PHP  99. lessc->reduce() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\inc\lessc.inc.php:621
> 

[Slack Reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1491990630612837)

**Comment by gregpriday** [comment]
@AlexGStapleton what are the exact steps to recreate this issue? I've installed the plugin and run an optimization, plus viewed a Page Builder page. Not sure where or when this is coming up.

**Comment by AlexGStapleton** [comment]
I, uh, enabled it and then viewed the home page which was set up to display the full content of a bunch of recent posts. Could this issue actually be related to generating things for a bunch of posts all at once rather than WP-Optimize?

Admitally, I haven't had any issues since posting and I've had WP-Optimize enabled the entire time.

**Comment by gregpriday** [comment]
I fixed up that warning from `SITEORIGIN_PANELS_BASE_FILE`. That was coming up with legacy widgets.

For the infinite loop, it looks like that's happening with an interaction between Yoast SEO, Page Builder and WP Optimize. The one thing we can suggest for users seeing this conflict is enabling the new Page Builder cache.

So if they navigate to Settings > Page Builder and enable *Content Cache*. I'm not sure it'll fix it, but there's a small chance it will.

**Comment by AlexGStapleton** [comment]
Sweet. If this comes up again, I'll suggest the Contact Cache as a potential solution. I think that'll do for now.

**Comment by gregpriday** [comment]
@braamgenis is taking a little look at this, if he can't figure it out, then we can move on for now.

**Comment by braamgenis** [comment]
Is this still an issue? I don't remember what the outcome was of previous troubleshooting/debugging, but I can't seem to reproduce any issues anymore.

**Comment by AlexGStapleton** [comment]
This hasn't been brought up for at least a year so it's unlikely this is an issue still.
